version: '3.8'

services:
  web:
      build: .
      command: >
        sh -c "python manage.py migrate &&
               python manage.py collectstatic --noinput &&
               python manage.py runserver 0.0.0.0:8000"
      volumes:
        - .:/app
      ports:
        - "8000:8000"
      depends_on:
        - redis
        - db

  selenium:
    image: selenium/standalone-chrome
    ports:
      - "4444:4444"
    shm_size: 2gb


  celery:
    build: .
    command: celery -A djangoProjecttaknews worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
      - db

  celery-beat:
    build: .
    command: celery -A djangoProjecttaknews beat --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
      - db

  flower:
    build: .
    command: celery -A djangoProjecttaknews flower --port=5555
    ports:
      - "5555:5555"
    depends_on:
      - redis
      - db

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data: