# Generated by Django 5.2.1 on 2025-05-11 12:47

import ckeditor_uploader.fields
import django.db.models.deletion
import django.utils.timezone
import mptt.fields
import news.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام تگ')),
                ('slug', models.SlugField(unique=True, verbose_name='اسلاگ')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام دسته\u200cبندی')),
                ('slug', models.SlugField(unique=True, verbose_name='اسلاگ')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='news.category', verbose_name='دسته\u200cبندی والد')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی',
                'verbose_name_plural': 'دسته\u200cبندی\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('slug', models.SlugField(unique=True, verbose_name='اسلاگ')),
                ('summary', models.TextField(blank=True, max_length=300, verbose_name='چکیده مطلب')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='محتوا')),
                ('source', models.CharField(blank=True, max_length=200, null=True, verbose_name='منبع')),
                ('source_url', models.URLField(blank=True, null=True, verbose_name='لینک منبع')),
                ('author', models.CharField(max_length=50, verbose_name='نویسنده')),
                ('publish_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ انتشار')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('image', models.ImageField(upload_to=news.models.blog_image_path, verbose_name='تصویر شاخص')),
                ('image_caption', models.CharField(blank=True, max_length=200, verbose_name='عنوان تصویر')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('published', 'منتشر شده'), ('archived', 'بایگانی شده')], default='draft', max_length=10, verbose_name='وضعیت')),
                ('is_featured', models.BooleanField(default=False, verbose_name='مقاله ویژه')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='تعداد بازدید')),
                ('seo_title', models.CharField(blank=True, max_length=60, verbose_name='عنوان سئو')),
                ('seo_description', models.CharField(blank=True, max_length=160, verbose_name='توضیحات سئو')),
                ('categories', models.ManyToManyField(related_name='articles', to='news.category', verbose_name='دسته\u200cبندی\u200cها')),
                ('tags', models.ManyToManyField(related_name='articles', to='news.tag', verbose_name='تگ\u200cها')),
            ],
            options={
                'verbose_name': 'مقاله',
                'verbose_name_plural': 'مقالات',
                'ordering': ['-publish_date'],
            },
        ),
    ]
