# Generated by Django 5.2.1 on 2025-05-12 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_article_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapedArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('summary', models.TextField()),
                ('content', models.TextField()),
                ('source_url', models.URLField()),
                ('publish_date', models.DateTimeField()),
                ('image_url', models.URLField(blank=True)),
                ('source', models.CharField(max_length=100)),
                ('tags', models.CharField(blank=True, max_length=255)),
                ('is_imported', models.BooleanField(default=False)),
            ],
        ),
    ]
